/**
 * Created by kekodmc on 2017/3/9.
 * 虚拟数据包
 */

var dataJson={
    data:[{
        type:'1',//预留
        name:'hello',//楼层名称
        maxTemp:'38.1',//最高温度
        minTemp:'3.0',//最低温度
        inTemp:'39.0',//室内温度
        outTemp:'23.1',//室外温度
        inWet:'15%',//室内湿度
        outWet:'37%',//室外湿度
        time:'2017-03-12 16:13:10',//采样时间
        avgTemp:'23.7',//平均温度
        area:[
           {
                name:'al',
                temperature:'9.0',
            },
            {
                name:'a2',
                temperature:'3.0'
            },
            {
                name:'a3',
                temperature:'14.8'
            },
            {
                name:'a4',
                temperature:'26.0'
            },
           {
                name:'a5',
                temperature:'35.1'
            },
            {
                name:'a6',
                temperature:'27.0'
            },
            {
                name:'al',
                temperature:'6.0',
            },
            {
                name:'a2',
                temperature:'19.0'
            },
            {
                name:'a3',
                temperature:'14.8'
            },
            {
                name:'a4',
                temperature:'26.0'
            },
            {
                name:'a5',
                temperature:'35.1'
            },
            {
                name:'a6',
                temperature:'27.0'
            },
            {
                name:'a2',
                temperature:'3.0'
            },
            {
                name:'a3',
                temperature:'14.8'
            },
            {
                name:'a4',
                temperature:'26.0'
            },
            {
                name:'a5',
                temperature:'35.1'
            }
        ]
    },
        {
            type:'1',
            name:'hello',
            maxTemp:'35.1',
            minTemp:'3.0',
            inTemp:'22.0',
            outTemp:'33.1',
            inWet:'13%',
            outWet:'34%',
            time:'2017-03-12 16:18:10',//采样时间
            avgTemp:'22.7',
            area:[
                {
                    name:'al',
                    temperature:'9.0',
                },
                {
                    name:'a2',
                    temperature:'3.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                },
                {
                    name:'a6',
                    temperature:'27.0'
                },
                {
                    name:'al',
                    temperature:'6.0',
                },
                {
                    name:'a2',
                    temperature:'19.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                },
                {
                    name:'a6',
                    temperature:'27.0'
                },
                {
                    name:'a2',
                    temperature:'23.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                }
            ]
        },
        {
            type:'1',
            name:'hello',
            maxTemp:'35.1',
            minTemp:'3.0',
            inTemp:'35.0',
            outTemp:'33.1',
            inWet:'10%',
            outWet:'30%',
            time:'2017-03-12 16:13:10',//采样时间
            avgTemp:'19.7',
            area:[
                {
                    name:'al',
                    temperature:'9.0',
                },
                {
                    name:'a2',
                    temperature:'9.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                },
                {
                    name:'a6',
                    temperature:'27.0'
                },
                {
                    name:'al',
                    temperature:'6.0',
                },
                {
                    name:'a2',
                    temperature:'19.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                },
                {
                    name:'a6',
                    temperature:'27.0'
                },
                {
                    name:'a2',
                    temperature:'19.0'
                },
                {
                    name:'a3',
                    temperature:'14.8'
                },
                {
                    name:'a4',
                    temperature:'26.0'
                },
                {
                    name:'a5',
                    temperature:'35.1'
                }
            ]
        }]
};